version: '2.0'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    links:
      - "influxdb"
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/:ro
      - ./grafana/dashboard-providers/:/etc/grafana/provisioning/dashboards/:ro
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/:ro
    environment:
      - INFLUXDB_DB=pwutseltronics
      - INFLUXDB_USER=telegraf

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=pwutseltronics
      - INFLUXDB_USER=telegraf

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    links:
      - "influxdb"
      - "mosquitto"
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
