{
 "title": "Energy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Elektrisch vermogen",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Elektrisch vermogen",
     "measurement": "electricity",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "P_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas vermogen (5 min. gemiddelde)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gas vermogen",
     "measurement": "gas",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ "1h" ], "type": "derivative" },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netspanning",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "V_L1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elektriciteitsverbruik vandaag",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"delivered_high\" + \"delivered_low\" FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbruik vandaag",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "litre",
   "valueName": "diff",
   "targets": [
    {
     "alias": "Gasverbruik vandaag",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energieverbruik gas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "kwatth",
   "valueName": "diff",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "litre" }
   ],
   "targets": [
    {
     "alias": "Liter/meetpunt",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbruiksvermogen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Elektrisch vermogen",
     "measurement": "electricity",
     "query": "SELECT \"P_total\"  *1000 FROM \"energy\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "P_total" ], "type": "field" },
       { "params": [ " *1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Teruglevering",
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "P_total_redelivery" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Gas equivalent vermogen",
     "measurement": "gas",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ "1h" ], "type": "derivative" },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netspanning",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "L1",
     "measurement": "electricity",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "V_L1" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (hoog tarief)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Geconsumeerde dure stroom",
     "measurement": "electricity",
     "query": "SELECT last(\"delivered_high\") FROM \"energy\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "delivered_high" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (laag tarief)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Geconsumeerde goedkope stroom",
     "measurement": "electricity",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "delivered_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas meterstand",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "m3",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (totaal)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 17 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"delivered_high\") + last(\"delivered_low\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas meterstand (energie eq.)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spanningsdips",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "L1_sags" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spanningspieken",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "L1_swells" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uitvallen",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lange uitvallen",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "format": "none",
   "valueName": "diff",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "long_failures" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bericht energieleverancier",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}