{
 "title": "Energy LT",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "hoogTarief", "query": "0.2038" },
   { "name": "laagTarief", "query": "0.1903" },
   { "name": "gasPrijs", "query": "0.83" }
  ]
 },
 "panels": [
  {
   "title": "Elektrisch verbruik",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatth", "label": "Verbruik" }
   ],
   "targets": [
    {
     "alias": "Laag tarief",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "delivered_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Hoog tarief",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity",
     "query": "SELECT difference(last(\"delivered_high\")) AS \"Hoog tarief\", difference(last(\"delivered_low\")) AS \"Laag tarief\" FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "delivered_high" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Totaal verbruik",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (difference(last(\"delivered_high\"))+difference(last(\"delivered_low\"))) FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Stroomkosten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"delivered_high\"))*$hoogTarief+difference(last(\"delivered_low\"))*$laagTarief FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elektriciteitsverbruik",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"delivered_high\") - first(\"delivered_high\") + last(\"delivered_low\") - first(\"delivered_low\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "litre",
   "valueName": "current",
   "targets": [
    {
     "alias": "Gasverbruik",
     "measurement": "gas",
     "query": "SELECT (last(\"gas_reading\") - first(\"gas_reading\")) *1000 FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energieverbruik gas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT (last(\"gas_reading\") - first(\"gas_reading\"))  * 31.65 / 3.6 FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energiekosten",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "alias": "Elektriciteit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(last(\"delivered_high\"))*$hoogTarief + difference(last(\"delivered_low\"))*$laagTarief FROM \"electricity\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT difference(last(\"gas_reading\")) FROM \"gas\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*$gasPrijs" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasverbruik",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "m3", "label": "Verbruik" }
   ],
   "targets": [
    {
     "alias": "m³ aardgas",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT difference(last(\"gas_reading\")) FROM \"gas\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "kg CO₂",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "*1.78" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (hoog tarief)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Geconsumeerde dure stroom",
     "measurement": "electricity",
     "query": "SELECT last(\"delivered_high\") FROM \"energy\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "delivered_high" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (laag tarief)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Geconsumeerde goedkope stroom",
     "measurement": "electricity",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "delivered_low" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas meterstand",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "format": "m3",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Meterstand (totaal)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 16 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"delivered_high\") + last(\"delivered_low\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas meterstand (energie eq.)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Total consumed",
     "measurement": "gas",
     "query": "SELECT SUM(\"value\") FROM (SELECT * FROM \"mqtt_consumer\" WHERE \"topic\" =~ /whiskeygrid\\/energy\\/mains\\/reading\\/delivered\\/(high|low)/ ORDER BY time DESC LIMIT 2) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "gas_reading" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 31.65 / 3.6" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netspanning",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "V_L1" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Gemiddeld",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "V_L1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity",
     "query": "SELECT \"value\" FROM \"mqtt_consumer\".\"*\" WHERE (\"topic\" = 'whiskeygrid/energy/mains/power/total') AND $timeFilter",
     "select": [
      [
       { "params": [ "V_L1" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spanningsdips",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "electricity",
     "query": "SELECT last(\"L1_sags\") - first(\"L1_sags\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "L1_sags" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spanningspieken",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "electricity",
     "query": "SELECT last(\"L1_swells\") - first(\"L1_swells\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "L1_swells" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uitvallen",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "electricity",
     "query": "SELECT last(\"failures\") - first(\"failures\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "failures" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lange uitvallen",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "electricity",
     "query": "SELECT last(\"long_failures\") - first(\"long_failures\") FROM \"electricity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "long_failures" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bericht energieleverancier",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}